project: 
  type: website
  output-dir: docs
  
website:
  favicon: favicon.png
  title: Making the most of Integral
  navbar:
    title: false
    background: light
    pinned: true
    search: false
    collapse: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Student"
        file: Student.qmd
      - text: "Teacher"
        file: Teacher.qmd
      - text: "Help/FAQ"
        file: help.qmd
      - text: Roadmap
        file: roadmap.qmd
    right: 
      - icon: twitter 
        href: https://twitter.com/integral_maths
    logo: logonew.png
    logo-alt: "Integral logo"
  page-footer: 
    left: "Copyright MEI, 2023" 
    

format:
  html:
    theme:
      - mystyles.scss
    mainfont: Work Sans
    toc: false

editor: visual

