## Learn

In this section, you will find the tools for the learning pat of the chapter. You will see:

-   Interactive books

-   Notes and Examples

-   Walkthroughs

-   Teaching videos

### Interactive books

These are throughout A Level Maths and can be used to introduce a new topic with learning or to revise for a topic. They have a mixture of notes, examples and questions. You will see multiple choice, drag and drop, flashcard type questions as well as others.

You can mark your answers instantly but these marks are just for you - **they are not reported back to your teacher.**

These are designed to work on all devices including mobiles.

### Notes and Examples

These are your typical, text book style notes and examples. Every chapter of every topic has notes and examples to help you learn.

### Walkthroughs

These are designed to *walk you through* a topic. They have an interactive element and contain questions to answer as practice which can be instantly marked.

These are best used on a laptop or computer.

### Teaching videos

There are over 1600 videos on Integral covering all of maths and further maths. Use these to catch up on missed topics or to re-enforce the teaching from class. You will see different examples to topics and they can help to round out your understanding.
