# Using Integral to practise

Maybe you have homework due. Maybe it is coming up to a test or a mock exam. Maybe it's nearly the summer exams......

Whatever the time of year, practice is the most important thing to do to get better at maths. You simply can not improve your maths by just reading.

Integral has you covered.

There are several options within Integral when you want to practise your maths.

## Interactive books

These are one of the newer additions to our A level maths resources. These books are designed to introduce a topic but they also make wonderful revision books. They have lots of different types of interactive questions throughout each book; all giving instant feedback when you answer them.

## Skillpacks

You won't find these in every section. However, throughout AS maths you will see them in the develop section. They are designed to give you examples of skill based questions and provide unlimited practice and feedback as you go.

## Leveled exercises

Throughout the topics you will find up to three levels of exercise. Each of them comes with **full worked solutions** so you can see line-by-line how the questions were answered.

### Level 1

These are a great place to practise the fundamentals of the topic.

### Level 2

These are designed to get you to an exam level of understanding.

### Level 3

These questions have been created to push your understanding of the topic to the max.

## Online self-marking tests

Every chapter has a specifically written online test. They are all self-marking for instant feedback on what was right and wrong. These can be difficult but have been designed to get you exam ready. You will need to have pen and paper (and calculator!) at the ready for all your workings as you will only put the answer into Integral.

## Topic assessments

Every topic comes with a topic assessment with marks ranging from 30 to 60. These are a challenging test of all you know from the chapters of the topic. As a student, you **do not** have access to the worked solutions so you may need to speak to your teacher about how best to use these assessments.
